### ISSUE TITLE
Python2 UnicodeDecodeError leads to connection failures

### ISSUE THREAD

**Issue by rinzes** [gehaxelt/python-rss2irc#14]
I have one config that I am unable to connect to the server.

Chicago.IL.US.Othernet.org

**Comment by gehaxelt** [comment]
Does the server allow unencrypted connections? Might be related to #3

**Comment by rinzes** [comment]
Yes the server allows unencrypted connections?

**Comment by gehaxelt** [comment]
Hi,
sorry for the late reply. I tried to connect to the server. The connection itself works, but then an error occurrs in one of the dependencies:

```
No handlers could be found for logger "jaraco.stream.buffer"
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/gehaxelt/Coding/Python/Rss2Irc/venv/lib/python2.7/site-packages/irc/bot.py", line 328, in start
    super(SingleServerIRCBot, self).start()
  File "/home/gehaxelt/Coding/Python/Rss2Irc/venv/lib/python2.7/site-packages/irc/client.py", line 1249, in start
    self.reactor.process_forever()
  File "/home/gehaxelt/Coding/Python/Rss2Irc/venv/lib/python2.7/site-packages/irc/client.py", line 278, in process_forever
    self.process_once(timeout)
  File "/home/gehaxelt/Coding/Python/Rss2Irc/venv/lib/python2.7/site-packages/irc/client.py", line 259, in process_once
    self.process_data(i)
  File "/home/gehaxelt/Coding/Python/Rss2Irc/venv/lib/python2.7/site-packages/irc/client.py", line 216, in process_data
    c.process_data()
  File "/home/gehaxelt/Coding/Python/Rss2Irc/venv/lib/python2.7/site-packages/irc/client.py", line 579, in process_data
    for line in self.buffer:
  File "/home/gehaxelt/Coding/Python/Rss2Irc/venv/lib/python2.7/site-packages/jaraco/stream/buffer.py", line 104, in lines
    self.handle_exception()
  File "/home/gehaxelt/Coding/Python/Rss2Irc/venv/lib/python2.7/site-packages/jaraco/stream/buffer.py", line 102, in lines
    yield line.decode(self.encoding, self.errors)
  File "/home/gehaxelt/Coding/Python/Rss2Irc/venv/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa9 in position 46: invalid start byte
```

Right now, I don't have any ideas how to fix that. Any help is welcome.
