### ISSUE TITLE
Some RSS feeds Result in Encoding issue

### ISSUE THREAD

**Issue by zigsphere** [gehaxelt/python-rss2irc#43]
RSS feeds such as http://www.arrl.org/news/rss throw error:

> (env) arrl@ircbot:~/arrl$ python2 feedupdater.py 
> 'ascii' codec can't encode character u'\u2019' in position 60: ordinal not in range(128)
> Failed: ARRL
> Exception in thread Thread-1 (most likely raised during interpreter shutdown):
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
>   File "/opt/arrl/env/local/lib/python2.7/site-packages/sqlite3worker/sqlite3worker.py", line 90, in run
>   File "/usr/lib/python2.7/Queue.py", line 168, in get
>   File "/usr/lib/python2.7/threading.py", line 333, in wait
> <type 'exceptions.TypeError'>: 'NoneType' object is not callable

**Comment by gehaxelt** [comment]
Hi @zigsphere 
thanks for the issue! 
Unfortunately, I don't have much spare time to work on it right now. 

It might be an issue with storing the data in the sqlite database (around https://github.com/gehaxelt/python-rss2irc/blob/master/feedupdater.py#L77)
